src/Berny/DemoBundle/Form/Type/FilterType.php
<?php

/*
 * This file is part of the form-filters package
 *
 * (c) Berny Cantos <be@rny.cc>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Berny\DemoBundle\Form\Type;

use Berny\DemoBundle\Form\Listener\ResetIndexesListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class FilterType extends AbstractType
{
    public function getName()
    {
        return 'filter';
    }

    public function getParent()
    {
        return 'collection';
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addEventSubscriber(new ResetIndexesListener());
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['prototype_name'] = $options['prototype_name'];
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setRequired(array(
            'filtered',
        ));
        $resolver->setDefaults(array(
            'type' => new CriterionType(),
            'allow_add' => true,
            'label' => false,
            'options' => array(
                'label' => false,
                'attr' => array(
                    'class' => 'criterion',
                ),
                'required' => false,
            ),
            'attr' => array(
                'class' => 'filter',
            ),
        ));
    }
}

src/Berny/DemoBundle/Resources/views/form-theme.html.twig
{% use "form_div_layout.html.twig" %}

{# Widgets #}

{% block form_widget_compound %}
{% spaceless %}
    <ul {{ block('widget_container_attributes') }}>
        {% if form.parent is empty %}
            {{ form_errors(form) }}
        {% endif %}
        {{ block('form_rows') }}
        {{ form_rest(form) }}
    </ul>
{% endspaceless %}
{% endblock form_widget_compound %}

{% block collection_widget %}
{% spaceless %}
    {% if prototype_name is defined %}
        {% set attr = attr|merge({
            'data-prototype-name': prototype_name
        }) %}
    {% endif %}
    {{ parent() }}
{% endspaceless %}
{% endblock %}

{% block choice_widget_expanded %}
{% spaceless %}
    <ul {{ block('widget_container_attributes') }}>
        {% for child in form %}
            {{ form_widget(child) }}
            {{ form_label(child) }}
        {% endfor %}
    </ul>
{% endspaceless %}
{% endblock choice_widget_expanded %}

{# Rows #}

{% block form_row %}
{% spaceless %}
    <li>
        {{ form_label(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form) }}
    </li>
{% endspaceless %}
{% endblock form_row %}

{% block button_row %}
{% spaceless %}
    <li>
        {{ form_widget(form) }}
    </li>
{% endspaceless %}
{% endblock button_row %}

src/Berny/DemoBundle/Resources/views/layout.html.twig
{% extends '::base.html.twig' %}

{% block body %}
    <h1>{{ block('title') }}</h1>
    <main>
        {% block content '' %}
    </main>
{% endblock %}

{% block sheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/bernydemo/css/main.css') }}" />
{% endblock %}